
# Initial pose
euroc_ros_msgs/TransformationXyzAbc initPose

# Final pose
euroc_ros_msgs/TransformationXyzAbc finalPose

# pick from the right sie
bool pickFromRight

# Motion parameters
euroc_ros_msgs/MotionParameters parameter

---

#Error message indicating failure - empty string = success
string error_message
