#Move the TCP (tool center point) relative to the current pose 
#in impedance mode while executing a sine motion 

#The relative transformation
TransformationXyzAbc transformation

#The desired stiffness in the 6 DoF of the TCP in [N] or [Nm]
SixDoF stiffness

#The desired amplitude in the 6 DoF of the sine motion of the TCP in [m] or [rad]
SixDoF amplitude

#The desired frequency in the 6 DoF of the sine motion of the TCP in [Hz]
SixDoF frequency

#The motion parameters
MotionParameters parameter

---

#Error message indicating failure - empty string = success
string error_message