#Move the TCP (tool center point) relative to the current pose

#The relative transformation
TransformationXyzAbc transformation

#The motion parameters
MotionParameters parameter

---

#Error message indicating failure - empty string = success
string error_message