<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="pan_tilt_connector_box" params="x y z material *origin">
      <visual>
        <xacro:insert_block name="origin"/>
        <geometry>
          <box size="${x} ${y} ${z}"/>
        </geometry>
        <material name="${material}"/>
      </visual>
      <collision>
        <xacro:insert_block name="origin"/>
        <geometry>
          <box size="${x} ${y} ${z}"/>
        </geometry>
        <material name="${material}"/>
      </collision>
   </xacro:macro>

  <xacro:macro name="pan_tilt_connector" params="parent_link name *origin">
    <joint name="${name}_fixed_base_joint" type="fixed">
       <xacro:insert_block name="origin"/>
       <child link="${name}_link" />
       <parent link="${parent_link}"/>
    </joint>

    <link name="${name}_link">
      <xacro:pan_tilt_connector_box
        x="0.065" y="0.065" z="0.003"
        material="Light Grey">
        <origin xyz="0 0 0.002" rpy="0 0 0"/>
      </xacro:pan_tilt_connector_box>

      <xacro:pan_tilt_connector_box
        x="0.2" y="0.04" z="0.022"
        material="Grey">
        <origin xyz="0 0 ${0.011 + 0.004}" rpy="0 0 0"/>
      </xacro:pan_tilt_connector_box>


      <!--inertial>
        <estimated from geometry and density of alumium>
        <origin xyz="0 0 ${0.5 * mast_height}" rpy="0 0 0" />
        <mass value="6.3" />
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
        </inertial-->
    </link>

    <gazebo reference="${name}_link">
      <material>Gazebo/Grey</material>
      <mu1>0.2</mu1>
      <mu2>0.2</mu2>
    </gazebo>

  </xacro:macro>

</robot>
