# Specifies a position of the platform with uncertainty information

# The x position [m]
float64 x

# The y position [m]
float64 y

# The theta orientation [rad]
float64 theta

# The x covariance [m^2]
float64 cov_xx

# The y covariance [m^2]
float64 cov_yy

# The theta covariance [rad^2]
float64 cov_thetatheta

# The x, y covariance [m^2]
float64 cov_xy

# The x, theta covariance [m * rad]
float64 cov_xtheta

# The y, theta covariance [m * rad]
float64 cov_ytheta

