# Specifies the state of the TCP (tool center point)

# The time stamp at which the measurement was taken (only qualitative but monotonically increasing)
time stamp

# The current pose commanded to the controller in [m] and [rad]
TransformationXyzAbc commanded_pose

# The estimated external force applied to the TCP in [N] and [Nm]
SixDoF external_force

# The current pose of the TCP in [m] and [rad]
TransformationXyzAbc pose

# The current pose of the flange in [m] and [rad]
TransformationXyzAbc flange_pose

