# Specifies a transformation in 6 DoF based on the KUKA notation.
# The convention is to first turn arround the z axis (a), then turn arround
# the y axis (b) and then turn arround the x axis (c)

# The x coordinate in [m]
float64 x

# The y coordinate in [m]
float64 y

# The z coordinate in [m]
float64 z

# The rotation around the z axis [rad]
float64 a

# The rotation around the y axis [rad]
float64 b

# The rotation around the x axis [rad]
float64 c
